#import <Foundation/Foundation.h>
#import "SWGObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */



@protocol SWGActivity
@end

@interface SWGActivity : SWGObject

/* Unique identifier for the activity [optional]
 */
@property(nonatomic) NSString* uuid;

@end
