#import <Foundation/Foundation.h>
#import "SWGObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

#import "SWGActivity.h"


@protocol SWGActivities
@end

@interface SWGActivities : SWGObject

/* Position in pagination. [optional]
 */
@property(nonatomic) NSNumber* offset;
/* Number of items to retrieve (100 max). [optional]
 */
@property(nonatomic) NSNumber* limit;
/* Total number of items available. [optional]
 */
@property(nonatomic) NSNumber* count;

@property(nonatomic) NSArray<SWGActivity>* history;

@end
