#import <Foundation/Foundation.h>
#import "SWGPriceEstimate.h"
#import "SWGError.h"
#import "SWGProduct.h"
#import "SWGObject.h"
#import "SWGApiClient.h"


/**
 * NOTE: This class is auto generated by the swagger code generator program. 
 * https://github.com/swagger-api/swagger-codegen 
 * Do not edit the class manually.
 */

@interface SWGEstimatesApi: NSObject

@property(nonatomic, assign)SWGApiClient *apiClient;

-(instancetype) initWithApiClient:(SWGApiClient *)apiClient;
-(void) addHeader:(NSString*)value forKey:(NSString*)key;
-(unsigned long) requestQueueSize;
+(SWGEstimatesApi*) apiWithHeader:(NSString*)headerValue key:(NSString*)key;
+(SWGEstimatesApi*) sharedAPI;
///
///
/// Price Estimates
/// The Price Estimates endpoint returns an estimated price range\nfor each product offered at a given location. The price estimate is\nprovided as a formatted string with the full price range and the localized\ncurrency symbol.<br><br>The response also includes low and high estimates,\nand the [ISO 4217](http://en.wikipedia.org/wiki/ISO_4217) currency code for\nsituations requiring currency conversion. When surge is active for a particular\nproduct, its surge_multiplier will be greater than 1, but the price estimate\nalready factors in this multiplier.
///
/// @param startLatitude Latitude component of start location.
/// @param startLongitude Longitude component of start location.
/// @param endLatitude Latitude component of end location.
/// @param endLongitude Longitude component of end location.
/// 
///
/// @return NSArray<SWGPriceEstimate>*
-(NSNumber*) estimatesPriceGetWithCompletionBlock :(NSNumber*) startLatitude 
     startLongitude:(NSNumber*) startLongitude 
     endLatitude:(NSNumber*) endLatitude 
     endLongitude:(NSNumber*) endLongitude 
    
    completionHandler: (void (^)(NSArray<SWGPriceEstimate>* output, NSError* error))completionBlock;
    


///
///
/// Time Estimates
/// The Time Estimates endpoint returns ETAs for all products offered at a given location, with the responses expressed as integers in seconds. We recommend that this endpoint be called every minute to provide the most accurate, up-to-date ETAs.
///
/// @param startLatitude Latitude component of start location.
/// @param startLongitude Longitude component of start location.
/// @param customerUuid Unique customer identifier to be used for experience customization.
/// @param productId Unique identifier representing a specific product for a given latitude &amp; longitude.
/// 
///
/// @return NSArray<SWGProduct>*
-(NSNumber*) estimatesTimeGetWithCompletionBlock :(NSNumber*) startLatitude 
     startLongitude:(NSNumber*) startLongitude 
     customerUuid:(NSString*) customerUuid 
     productId:(NSString*) productId 
    
    completionHandler: (void (^)(NSArray<SWGProduct>* output, NSError* error))completionBlock;
    



@end
