#import <Foundation/Foundation.h>
#import "SWGProduct.h"
#import "SWGError.h"
#import "SWGObject.h"
#import "SWGApiClient.h"


/**
 * NOTE: This class is auto generated by the swagger code generator program. 
 * https://github.com/swagger-api/swagger-codegen 
 * Do not edit the class manually.
 */

@interface SWGProductsApi: NSObject

@property(nonatomic, assign)SWGApiClient *apiClient;

-(instancetype) initWithApiClient:(SWGApiClient *)apiClient;
-(void) addHeader:(NSString*)value forKey:(NSString*)key;
-(unsigned long) requestQueueSize;
+(SWGProductsApi*) apiWithHeader:(NSString*)headerValue key:(NSString*)key;
+(SWGProductsApi*) sharedAPI;
///
///
/// Product Types
/// The Products endpoint returns information about the *Uber* products\noffered at a given location. The response includes the display name\nand other details about each product, and lists the products in the\nproper display order.
///
/// @param latitude Latitude component of location.
/// @param longitude Longitude component of location.
/// 
///
/// @return NSArray<SWGProduct>*
-(NSNumber*) productsGetWithCompletionBlock :(NSNumber*) latitude 
     longitude:(NSNumber*) longitude 
    
    completionHandler: (void (^)(NSArray<SWGProduct>* output, NSError* error))completionBlock;
    



@end
