#import <Foundation/Foundation.h>
#import "SWGObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */



@protocol SWGProfile
@end

@interface SWGProfile : SWGObject

/* First name of the Uber user. [optional]
 */
@property(nonatomic) NSString* firstName;
/* Last name of the Uber user. [optional]
 */
@property(nonatomic) NSString* lastName;
/* Email address of the Uber user [optional]
 */
@property(nonatomic) NSString* email;
/* Image URL of the Uber user. [optional]
 */
@property(nonatomic) NSString* picture;
/* Promo code of the Uber user. [optional]
 */
@property(nonatomic) NSString* promoCode;

@end
