#import <Foundation/Foundation.h>
#import "SWGObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */



@protocol SWGProduct
@end

@interface SWGProduct : SWGObject

/* Unique identifier representing a specific product for a given latitude & longitude. For example, uberX in San Francisco will have a different product_id than uberX in Los Angeles. [optional]
 */
@property(nonatomic) NSString* productId;
/* Description of product. [optional]
 */
@property(nonatomic) NSString* _description;
/* Display name of product. [optional]
 */
@property(nonatomic) NSString* displayName;
/* Capacity of product. For example, 4 people. [optional]
 */
@property(nonatomic) NSString* capacity;
/* Image URL representing the product. [optional]
 */
@property(nonatomic) NSString* image;

@end
