#import <Foundation/Foundation.h>
#import "SWGActivities.h"
#import "SWGError.h"
#import "SWGProfile.h"
#import "SWGObject.h"
#import "SWGApiClient.h"


/**
 * NOTE: This class is auto generated by the swagger code generator program. 
 * https://github.com/swagger-api/swagger-codegen 
 * Do not edit the class manually.
 */

@interface SWGUserApi: NSObject

@property(nonatomic, assign)SWGApiClient *apiClient;

-(instancetype) initWithApiClient:(SWGApiClient *)apiClient;
-(void) addHeader:(NSString*)value forKey:(NSString*)key;
-(unsigned long) requestQueueSize;
+(SWGUserApi*) apiWithHeader:(NSString*)headerValue key:(NSString*)key;
+(SWGUserApi*) sharedAPI;
///
///
/// User Activity
/// The User Activity endpoint returns data about a user's lifetime activity with Uber. The response will include pickup locations and times, dropoff locations and times, the distance of past requests, and information about which products were requested.<br><br>The history array in the response will have a maximum length based on the limit parameter. The response value count may exceed limit, therefore subsequent API requests may be necessary.
///
/// @param offset Offset the list of returned results by this amount. Default is zero.
/// @param limit Number of items to retrieve. Default is 5, maximum is 100.
/// 
///
/// @return SWGActivities*
-(NSNumber*) historyGetWithCompletionBlock :(NSNumber*) offset 
     limit:(NSNumber*) limit 
    
    completionHandler: (void (^)(SWGActivities* output, NSError* error))completionBlock;
    


///
///
/// User Profile
/// The User Profile endpoint returns information about the Uber user that has authorized with the application.
///
/// 
///
/// @return SWGProfile*
-(NSNumber*) meGetWithCompletionBlock :
    (void (^)(SWGProfile* output, NSError* error))completionBlock;
    



@end
